# Generated by Django 3.2.6 on 2021-08-07 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleQuestionGenerator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='creatorOccupation',
        ),
    ]
