# Generated by Django 3.2.6 on 2021-08-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpleQuestionGenerator', '0003_auto_20210807_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='planName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simpleQuestionGenerator.plan'),
        ),
    ]
