# Generated by Django 3.2.6 on 2021-08-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleQuestionGenerator', '0004_creator_planname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='planName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
