# Generated by Django 3.2.6 on 2021-08-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleQuestionGenerator', '0006_plan_plandescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='creatorEmail',
        ),
    ]
