# Generated by Django 3.2.6 on 2021-08-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleQuestionGenerator', '0007_remove_creator_creatoremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='planStatus',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
